// Generated by CoffeeScript 1.7.1
$(function() {
  var app;

  app = angular.module('app', ['selectAddress']);

  app.controller('appCtrl', function($scope) {
    $scope.p = '江西';
    $scope.c = '南昌';
    $scope.a = '南昌县';
    return $scope.d = '';
  });

  angular.bootstrap(document, ['app']);

});

//# sourceMappingURL=index.map
